Improved some text formatting.

diff --git a/typedef b/typedef
--- a/typedef
+++ b/typedef
@@ -1,93 +1,101 @@
 #!/QOpenSys/usr/bin/sh
 
-### Generates a C-style typedef for a given externally-described file
-### 
-### Written by Jeff Berman, 2016-10-04
+# Generates a C-style typedef for a given externally-described file
+# 
+# Written by Jeff Berman, 2016-10-04
 
 print_help() {
-	(echo "typedef -- generate typedef for externally-described files\n"
-	echo "Generates typedefs for an externally-described file to stdout.  This is a wrapper around GENCSRC, and converts its output to ASCII with Unix-style line endings.\n"
-	echo "Usage: typedef [-d] file library\n"
-	echo "EXAMPLE"
-	echo "     Generate typedef for file MYLIB/MYFILE."
-	echo "     \ttypedef MYFILE MYLIB\n") | fold -s
-		
-	exit 0
+   (echo "typedef -- generate typedef for externally-described files"
+    echo
+    echo "Generates typedefs for an externally-described file to stdout.  This is a wrapper around GENCSRC, and converts its output to ASCII with Unix-style line endings."
+    echo
+    echo "Usage: typedef [-d] file library"
+    echo
+	echo "  -d  Debug mode. Enables extra logging."
+    echo
+    echo "EXAMPLES"
+    echo "  Generate typedef for file MYLIB/MYFILE."
+    echo "      typedef MYFILE MYLIB"
+    echo
+    echo "  Generate typedef for file MYLIB/MYFILE, and write it to an IFS source file."
+    echo "      typedef MYFILE MYLIB > /Source/headers/MYFILE.PF.H") | fold -s
+        
+    exit 0
 } >&2
 
-### Print a string in upper case
+# Print a string in upper case
 print_upper() {
-	local string=$(echo "$1" | tr '[:lower:]' '[:upper:]')
-	echo $string
+    local string=$(echo "$1" | tr '[:lower:]' '[:upper:]')
+    echo $string
 }
 
-### Print the name of this script
+# Print the name of this script
 script_name() {
-	echo "${0##*/}"
+    echo "${0##*/}"
 }
-	
+    
 debug=false
 
-### Process options
+# Process options
 while getopts :d opt; do
-	case "$opt" in
-	d)	debug=true
-		;;
-	\?)	print_help
-		exit 1
-		;;
-	esac
+    case "$opt" in
+    d)  debug=true
+        ;;
+    \?) print_help
+        exit 1
+        ;;
+    esac
 done
 
-### Require two arguments
-shift $OPTIND-1
+# Require two arguments
+shift "$(($OPTIND-1))"
 
 if [ $# -ne 2 ]; then
-	print_help
-	exit 1
+    print_help
+    exit 1
 fi
 
 file=$(print_upper $1)
 lib=$(print_upper $2)
 
 if [[ "$lib" == "QSYS" ]]; then
-	path="/QSYS.LIB"
+    path="/QSYS.LIB"
 else
-	path=/QSYS.LIB/${lib}.LIB
+    path=/QSYS.LIB/${lib}.LIB
 fi
 
-### First check if file even exists; if not, we're all done.
+# First check if file even exists; if not, we're all done.
 if [ ! -e $path/${file}.FILE ]; then
-	echo "typedef: File $path/${file}.FILE doesn't exist; exiting." >&2
-	exit 0
+    echo "typedef: File $path/${file}.FILE doesn't exist; exiting." >&2
+    exit 0
 fi
 
-### Determine the type of file
+# Determine the type of file
 suffix=$(system "dspobjd ${lib}/${file} *file" | tail -n2 | head -n1 | awk '{print $3}')
 
-### Generate the typedef
+# Generate the typedef
 if [ "$suffix" = 'PRTF' ]; then
-	SLTFLD='*OUTPUT'
+    SLTFLD='*OUTPUT'
 else
-	SLTFLD='*BOTH *KEY'
+    SLTFLD='*BOTH *KEY'
 fi
 
 tempfile=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 10)
 
 if [ "$debug" == "true" ]; then
-	echo "typedef: file =\t\t$file"
-	echo "typedef: lib =\t\t$lib"
-	echo "typedef: suffix =\t$suffix"
-	echo "typedef: SLTFLD =\t$SLTFLD"
-	echo "typedef: tempfile =\t/tmp/$tempfile"
-	echo
+    echo "typedef: file =     $file"
+    echo "typedef: lib =      $lib"
+    echo "typedef: suffix =   $suffix"
+    echo "typedef: SLTFLD =   $SLTFLD"
+    echo "typedef: tempfile = /tmp/$tempfile"
+    echo
 fi >&2
 
 system -v "GENCSRC OBJ('$path/${file}.FILE') SRCSTMF('/tmp/${tempfile}') SLTFLD($SLTFLD) TYPEDEFPFX('$file')" > /dev/null
 
 if [ $? -ne 0 ]; then
-	echo "typefef: Error occurred calling GENCSRC." >&2
-	exit 1
+    echo "typefef: Error occurred calling GENCSRC." >&2
+    exit 1
 fi
 
 # The `sed` statement below converts 'int' to 'long int', as the SQL precompiler needs the type explicitly stated.
